name: My first workflow
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch: # Lancement manuel

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3

      - run: npm install

      - run: gulp build

      # Ajouter une étape pour vérifier si le dossier dest/ existe réellement
      - run: ls -l dest/

      - uses: actions/upload-artifact@v3
        with:
          name: MyPackage
          path: dest
